/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.FornecedorDAO;
import DTO.FornecedorDTO;
import java.awt.Color;
import static java.awt.Color.red;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Jm.JMascara;
import java.awt.Toolkit;
import org.apache.commons.lang3.text.WordUtils;

/**
 *
 * @author Hector
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
        initComplementos();
        ListarFornecedor();
        Icone();
    }

    public void initComplementos() {
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecoFornecedor = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();
        btnDeletar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JFormattedTextField();
        radioCodigo = new javax.swing.JRadioButton();
        radioNome = new javax.swing.JRadioButton();
        radioCnpj = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JFormattedTextField();
        btnLimpar = new javax.swing.JButton();
        txtNumero_Endereco = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCnpjFornecedor = new javax.swing.JFormattedTextField();
        txtTelefoneFornecedor = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Nome");

        txtNomeFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtNomeFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFornecedorActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botao-adicionar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Fornecedores");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("CNPJ");

        txtEnderecoFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtEnderecoFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEnderecoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoFornecedorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Endereço");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Telefone");

        txtEmailFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtEmailFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmailFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFornecedorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "CNPJ", "Endereço", "N°", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tabelaFornecedor.getTableHeader().setReorderingAllowed(false);
        tabelaFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFornecedor);

        btnDeletar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/excluir.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setBorderPainted(false);
        btnDeletar.setContentAreaFilled(false);
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletarMouseExited(evt);
            }
        });
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/intercambio.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setContentAreaFilled(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        txtPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtPesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        radioCodigo.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(radioCodigo);
        radioCodigo.setText("Codigo");

        radioNome.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(radioNome);
        radioNome.setText("Nome");

        radioCnpj.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(radioCnpj);
        radioCnpj.setText("CNPJ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Codigo");

        txtCodigo.setBackground(new java.awt.Color(153, 204, 255));
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/limpar.png"))); // NOI18N
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        txtNumero_Endereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtNumero_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero_EnderecoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("N°");

        txtCnpjFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtCnpjFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCnpjFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFornecedorActionPerformed(evt);
            }
        });
        txtCnpjFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCnpjFornecedorKeyReleased(evt);
            }
        });

        txtTelefoneFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtTelefoneFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefoneFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneFornecedorKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/voltar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSalvar))
                            .addComponent(txtCnpjFornecedor)
                            .addComponent(txtTelefoneFornecedor))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(radioCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioCnpj))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(302, 302, 302))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletar)
                            .addComponent(btnAlterar))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioCodigo)
                            .addComponent(radioNome)
                            .addComponent(radioCnpj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFornecedorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ValidarCamposCadastrar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtEnderecoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoFornecedorActionPerformed

    private void txtEmailFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFornecedorActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        ValidarCamposAlterar();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        ExcluirFornecedor();
        ListarFornecedor();
        LimparCampos();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        RadioCodigo();
        RadioNome();
        RadioCnpj();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void tabelaFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFornecedorMouseClicked
        CarregarCampos();
    }//GEN-LAST:event_tabelaFornecedorMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNumero_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero_EnderecoActionPerformed

    private void txtCnpjFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFornecedorActionPerformed

    private void txtCnpjFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjFornecedorKeyReleased
        txtCnpjFornecedor.setText(JMascara.GetJmascaraCpfCnpj(txtCnpjFornecedor.getText()));
    }//GEN-LAST:event_txtCnpjFornecedorKeyReleased

    private void txtTelefoneFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFornecedorKeyReleased
        txtTelefoneFornecedor.setText(JMascara.GetJmascaraFone(txtTelefoneFornecedor.getText()));
    }//GEN-LAST:event_txtTelefoneFornecedorKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio objinicio = new Inicio();
        objinicio.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseEntered
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnDeletarMouseEntered

    private void btnDeletarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseExited
        btnDeletar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnDeletarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCnpj;
    private javax.swing.JRadioButton radioCodigo;
    private javax.swing.JRadioButton radioNome;
    private javax.swing.JTable tabelaFornecedor;
    private javax.swing.JFormattedTextField txtCnpjFornecedor;
    private javax.swing.JFormattedTextField txtCodigo;
    private javax.swing.JFormattedTextField txtEmailFornecedor;
    private javax.swing.JFormattedTextField txtEnderecoFornecedor;
    private javax.swing.JFormattedTextField txtNomeFornecedor;
    private javax.swing.JFormattedTextField txtNumero_Endereco;
    private javax.swing.JFormattedTextField txtPesquisar;
    private javax.swing.JFormattedTextField txtTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables

    public void CadastrarFornecedor() {
        String nomeFornecedor, enderecoFornecedor, emailFornecedor, cnpjFornecedor, telefoneFornecedor;
        int numero_endereco;

        nomeFornecedor = WordUtils.capitalize(txtNomeFornecedor.getText());
        enderecoFornecedor = WordUtils.capitalize(txtEnderecoFornecedor.getText());
        emailFornecedor = txtEmailFornecedor.getText();
        cnpjFornecedor = txtCnpjFornecedor.getText();
        telefoneFornecedor = txtTelefoneFornecedor.getText();
        numero_endereco = Integer.parseInt(txtNumero_Endereco.getText());

        FornecedorDTO objfornecedordto = new FornecedorDTO();
        objfornecedordto.setNome_fornecedor(nomeFornecedor);
        objfornecedordto.setEndereco_fornecedor(enderecoFornecedor);
        objfornecedordto.setNumero_endereco(numero_endereco);
        objfornecedordto.setEmail_fornecedor(emailFornecedor);
        objfornecedordto.setCnpj_fornecedor(cnpjFornecedor);
        objfornecedordto.setTelefone_fornecedor(telefoneFornecedor);

        FornecedorDAO objfornecedordao = new FornecedorDAO();
        objfornecedordao.cadastrarFornecedor(objfornecedordto);
    }

    public void ListarFornecedor() {
        try {
            FornecedorDAO objfornecedordao = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();

            model.setNumRows(0);

            ArrayList<FornecedorDTO> lista = objfornecedordao.listarFornecedor();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_fornecedor(),
                    lista.get(num).getNome_fornecedor(),
                    lista.get(num).getCnpj_fornecedor(),
                    lista.get(num).getEndereco_fornecedor(),
                    lista.get(num).getNumero_endereco(),
                    lista.get(num).getTelefone_fornecedor(),
                    lista.get(num).getEmail_fornecedor()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na pesquisa!");
        }
    }

    public void BuscarFornecedorCodigo(String buscar) {
        try {
            FornecedorDAO objfornecedordao = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<FornecedorDTO> lista = objfornecedordao.buscarFornecedorCodigo(buscar);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_fornecedor(),
                    lista.get(num).getNome_fornecedor(),
                    lista.get(num).getCnpj_fornecedor(),
                    lista.get(num).getEndereco_fornecedor(),
                    lista.get(num).getNumero_endereco(),
                    lista.get(num).getTelefone_fornecedor(),
                    lista.get(num).getEmail_fornecedor()
                });

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na pesquisa!");
        }
    }

    public void BuscarFornecedorNome(String buscar) {
        try {
            FornecedorDAO objfornecedordao = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<FornecedorDTO> lista = objfornecedordao.buscarFornecedorNome(buscar);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_fornecedor(),
                    lista.get(num).getNome_fornecedor(),
                    lista.get(num).getCnpj_fornecedor(),
                    lista.get(num).getEndereco_fornecedor(),
                    lista.get(num).getNumero_endereco(),
                    lista.get(num).getTelefone_fornecedor(),
                    lista.get(num).getEmail_fornecedor()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na pesquisa!");
        }
    }

    public void BuscarFornecedorCnpj(String buscar) {
        try {
            FornecedorDAO objfornecedordao = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<FornecedorDTO> lista = objfornecedordao.buscarFornecedorCnpj(buscar);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_fornecedor(),
                    lista.get(num).getNome_fornecedor(),
                    lista.get(num).getCnpj_fornecedor(),
                    lista.get(num).getEndereco_fornecedor(),
                    lista.get(num).getNumero_endereco(),
                    lista.get(num).getTelefone_fornecedor(),
                    lista.get(num).getEmail_fornecedor()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na pesquisa!");
        }
    }

    private void CarregarCampos() {

        int setar = tabelaFornecedor.getSelectedRow();

        txtCodigo.setText(tabelaFornecedor.getModel().getValueAt(setar, 0).toString());
        txtNomeFornecedor.setText(tabelaFornecedor.getModel().getValueAt(setar, 1).toString());
        txtCnpjFornecedor.setText(tabelaFornecedor.getModel().getValueAt(setar, 2).toString());
        txtEnderecoFornecedor.setText(tabelaFornecedor.getModel().getValueAt(setar, 3).toString());
        txtNumero_Endereco.setText(tabelaFornecedor.getModel().getValueAt(setar, 4).toString());
        txtTelefoneFornecedor.setText(tabelaFornecedor.getModel().getValueAt(setar, 5).toString());
        txtEmailFornecedor.setText(tabelaFornecedor.getModel().getValueAt(setar, 6).toString());

    }

    private void LimparCampos() {

        txtCodigo.setText("");
        txtNomeFornecedor.setText("");
        txtCnpjFornecedor.setText("");
        txtEnderecoFornecedor.setText("");
        txtNumero_Endereco.setText("");
        txtTelefoneFornecedor.setText("");
        txtEmailFornecedor.setText("");
        txtNomeFornecedor.requestFocus();
    }

    private void AlterarFornecedor() {
        int id_fornecedor, numero_endereco;
        String nome_fornecedor, endereco_fornecedor, email_fornecedor, cnpj_fornecedor, telefone_fornecedor;

        id_fornecedor = Integer.parseInt(txtCodigo.getText());
        cnpj_fornecedor = txtCnpjFornecedor.getText();
        telefone_fornecedor = txtTelefoneFornecedor.getText();
        numero_endereco = Integer.parseInt(txtNumero_Endereco.getText());
        nome_fornecedor = WordUtils.capitalize(txtNomeFornecedor.getText());
        endereco_fornecedor =WordUtils.capitalize(txtEnderecoFornecedor.getText());
        email_fornecedor = txtEmailFornecedor.getText();

        FornecedorDTO objfornecedordto = new FornecedorDTO();
        objfornecedordto.setId_fornecedor(id_fornecedor);
        objfornecedordto.setNome_fornecedor(nome_fornecedor);
        objfornecedordto.setCnpj_fornecedor(cnpj_fornecedor);
        objfornecedordto.setEndereco_fornecedor(endereco_fornecedor);
        objfornecedordto.setNumero_endereco(numero_endereco);
        objfornecedordto.setTelefone_fornecedor(telefone_fornecedor);
        objfornecedordto.setEmail_fornecedor(email_fornecedor);

        FornecedorDAO objfornecedordao = new FornecedorDAO();
        objfornecedordao.alterarFornecedor(objfornecedordto);
    }

    public void ExcluirFornecedor() {
        int id_fornecedor;

        id_fornecedor = Integer.parseInt(txtCodigo.getText());

        FornecedorDTO objfornecedordto = new FornecedorDTO();
        objfornecedordto.setId_fornecedor(id_fornecedor);

        FornecedorDAO objfornecedordao = new FornecedorDAO();
        objfornecedordao.excluirFornecedor(objfornecedordto);
    }

    public void RadioCodigo() {
        if (radioCodigo.isSelected()) {
            BuscarFornecedorCodigo(txtPesquisar.getText());
        }
    }

    public void RadioNome() {
        if (radioNome.isSelected()) {
            BuscarFornecedorNome(txtPesquisar.getText());
        }
    }

    public void RadioCnpj() {
        if (radioCnpj.isSelected()) {
            BuscarFornecedorCnpj(JMascara.GetJmascaraCpfCnpj(txtPesquisar.getText()));
        }
    }

    public void ValidarCamposCadastrar() {
        if (txtNomeFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo nome é obrigatório, favor preencher!");
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.requestFocus();
            return;
        }
        if (txtCnpjFornecedor.getText().trim().length() < 18) {
            JOptionPane.showMessageDialog(null, "O campo cnpj é obrigatório, favor preencher!");
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtCnpjFornecedor.requestFocus();
            return;
        }
        if (txtEnderecoFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo endereço é obrigatório, favor preencher!");
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.requestFocus();
            return;
        }

        if (txtNumero_Endereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo numero de endereço é obrigatório, favor preencher!");
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        }

        if (txtTelefoneFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo telefone é obrigatório, favor preencher!");
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.requestFocus();
            return;
        }
        if (txtEmailFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo email é obrigatório, favor preencher!");
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.requestFocus();
            return;
        }
        txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        CadastrarFornecedor();
        LimparCampos();
        ListarFornecedor();

    }

    public void ValidarCamposAlterar() {
        if (txtNomeFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo nome é obrigatório, favor preencher!");
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.requestFocus();

            return;
        } else if (txtCnpjFornecedor.getText().trim().length() < 18) {
            JOptionPane.showMessageDialog(null, "O campo cnpj é obrigatório, favor preencher!");
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtCnpjFornecedor.requestFocus();
            return;
        }
        if (txtEnderecoFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo endereço é obrigatório, favor preencher!");
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.requestFocus();
            return;
        } else if (txtTelefoneFornecedor.getText().trim().length() < 13) {
            JOptionPane.showMessageDialog(null, "O campo telefone é obrigatório, favor preencher!");
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.requestFocus();
            return;
        }
        if (txtEmailFornecedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo email é obrigatório, favor preencher!");
            txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
            txtEmailFornecedor.requestFocus();
            return;

        }
        txtCnpjFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtNomeFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtEnderecoFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtTelefoneFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtEmailFornecedor.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        txtNumero_Endereco.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        AlterarFornecedor();
        LimparCampos();
        ListarFornecedor();
    }

    public void Icone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/sheriff-badge.png")));

    }
}
